site_name: Divvy
site_logo: img/divvy_logo_dark.svg
site_url: http://code.databio.org/divvy/
repo_url: http://github.com/databio/divvy

nav:
  - Getting Started: 
    - Introduction: README.md
  - How-to Guides:
    - Write a DIVCFG file: configuration.md
    - Configuring containers: containers.md
    - Using divvy interactively: tutorial.md
  - Reference:
    - API: autodoc_build/divvy.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md
    - DIVCFG examples: http://github.com/pepkit/pepenv

theme: databio

plugins:
  - databio
  - search

