site_name: Divvy
site_logo: img/divvy_logo_dark.svg
site_url: http://divvy.databio.org/
repo_url: http://github.com/databio/divvy
pypi_name: divvy

nav:
  - Getting Started: 
    - Introduction: README.md
    - "Tutorial: divvy in python": tutorial.md
    - "Tutorial: divvy on the command line": cli.md
  - How-to Guides:
    - Configuring divvy: configuration.md
    - Configuring containers: containers.md
  - Reference:
    - API: autodoc_build/divvy.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md
    - DIVCFG examples: http://github.com/pepkit/divcfg

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      autodoc_package: "divvy"
      no_top_level: true
  - search
