site_name: Divvy
nav:
  - Introduction: README.md
    
  - How-to Guides:
    - Writing divvy configuration files: configuration.md
    - Using divvy interactively: jupyter_build/tutorial.md

  - Reference:
    - API: autodoc_build/divvy.md
    - Support: support.md
    - Contributing: contributing.md

  - Changelog: changelog.md

#theme: readthedocs